### ISSUE TITLE
Meshkernel 2.0.2 does not work with numpy 1.24.3

### ISSUE THREAD

**Issue by xldeltares** [Deltares/MeshKernelPy#62]
**Describe the bug**
When import meshkernel with the latest numpy version (1.24.3), there is an ValueError.

**To Reproduce**
import meshkernel

**Expected behavior**

**Screenshots**
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\site-packages\meshkernel\__init__.py", line 4, in <module>
    from meshkernel.factories import Mesh2dFactory
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\site-packages\meshkernel\factories.py", line 4, in <module>
    from meshkernel.py_structures import Mesh2d
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\site-packages\meshkernel\py_structures.py", line 80, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\li_xn\AppData\Local\anaconda3\envs\hydromt-delft3dfm\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'numpy.ndarray'> for field face_nodes is not allowed: use default_factory
```

**Version info (please complete the following information):**
 - OS: [Windows]
 - Version [2.0.2]

**Comment by xldeltares** [comment]
Update: we have another environment with the same numpy verison 1.24.3 and meshkernel 2.0.2 installed, but that one is working. We could not figure out why. Please see attached environment file - this is the environment we are trying to generate for hydromt-delft3dfm (the previous hydrolib-hydromt). So far it fails on import meshkernel.  Also could you please indicate what dependencies are needed for installing meshkernel? Thanks! 

attachment: [hydromt-delft3dfm.zip](https://github.com/Deltares/MeshKernelPy/files/11849969/hydromt-delft3dfm.zip)

@rhutten could you please followup on this issue? thanks!

**Comment by veenstrajelmer** [comment]
@xldeltares are you using py3.11 by any chance? Please see this issue: https://github.com/Deltares/MeshKernelPy/issues/54

**Comment by xldeltares** [comment]
@veenstrajelmer we are indeed using py3.11. We will switch to py3.10 for now (before the new release) and see if that solves the issue. Thanks!

**Comment by xldeltares** [comment]
After downgrading to py3.10 the issue is solved.

**Comment by veenstrajelmer** [comment]
@xldeltares, meshkernel 2.1.0 was released yesterday and is now available via pip. Therefore, your installation should now also work with python 3.11
